#!/bin/bash

CC="cc -ansi -pedantic -lm"

run() {
	if [ $# -gt 0 ]; then
		FILE=$1
		if [ -f $FILE ]; then
			echo $CC $FILE
			$CC $FILE && ./a.out
		else
			echo $FILE not found
			exit 1
		fi
	fi
}

main() {
	if [ $# -gt 0 ]; then
		for FILE in $@; do
			run $FILE
		done
	else
		run main.c
	fi
	[ -f a.out ] && rm a.out
}

main $@
