#!/bin/bash

CC="cc -ansi -pedantic"

run() {
	if [ $# -gt 0 ]; then
		RUN=$CC
		for FILE in $@; do
			FILE="$FILE.c"
			[ -f "$FILE" ] && RUN="$RUN $FILE" || echo "$FILE not found"
		done
		[ "$RUN" != "$CC" ] && $RUN -lm && ./a.out
	fi
}

main() {
	if [ $# -gt 0 ]; then
		run $@
	else
		run "test"
	fi
	[ -f a.out ] && rm a.out
}

main $@
